name: CS Challenge

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Next Tag Version
      id: gettags
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.CS_TOKEN }}
        WITH_V: true
        DRY_RUN: true

    - name: Display Next Tag Version
      run: echo TAG generated is ${{ steps.gettags.outputs.new_tag }}
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DVERSION_TAG_CMD=${{ steps.gettags.outputs.new_tag }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DVERSION_TAG_CMD=${{ steps.gettags.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

